# Generated by Django 2.0.5 on 2019-08-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190707_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
    ]
