# Generated by Django 2.0.5 on 2019-08-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190819_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
